#!/bin/sh
### BEGIN INIT INFO
# Provides:          unicorn
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Manage unicorn servers
# Description:       Start, stop, restart unicorn servers for a ruby application.
### END INIT INFO

TEXT_RED=$(tput setaf 1)    # Red
TEXT_GRN=$(tput setaf 2)    # Green
TEXT_YEL=$(tput setaf 3)    # Yellow
TEXT_BLU=$(tput setaf 4)    # Blue
TEXT_PUR=$(tput setaf 5)    # Purple
TEXT_CYN=$(tput setaf 6)    # Cyan
TEXT_WHI=$(tput setaf 7)    # White
TEXT_RES=$(tput sgr0);      # Text color reset

set -e

while getopts c:i:e: option
do
  case "${option}"
  in
    c) COMMAND=${OPTARG};;
    i) INSTANCE=${OPTARG};;
    e) ENVIRONMENT=${OPTARG};;
  esac
done

if [ -z $ENVIRONMENT ]; then
  ENVIRONMENT="development"
fi

sig () {
  test -s "$PID" && kill -$1 `cat $PID`
}

oldsig () {
  test -s $OLD_PIN && kill -$1 `cat $OLD_PIN`
}

run_task() {
  . /etc/unicorn/$1.conf

  APP_ROOT=$app_root
  PID=$APP_ROOT/tmp/pids/unicorn.pid
  CMD="cd $APP_ROOT; bundle exec unicorn -D -c $APP_ROOT/config/unicorn.rb -E $ENVIRONMENT"
  AS_USER=$user

  run () {
    if [ "$(id -un)" = "$AS_USER" ]; then
      eval $1
    else
      su -c "$1" - $AS_USER
    fi
  }

  case "$COMMAND" in
  start)
    sig 0 && echo >&2 "${TEXT_RED}${1} already running${TEXT_RES}" && return 0
    run "$CMD"
    echo "${TEXT_GRN}${1} started in ${ENVIRONMENT} environment OK${TEXT_RES}"
    ;;
  stop)
    sig QUIT && echo "${TEXT_GRN}${1} stoped OK${TEXT_RES}" && return 0
    echo >&2 "${TEXT_RED}${1} not running${TEXT_RES}"
    ;;
  force-stop)
    sig TERM && echo "${TEXT_GRN}${1} force-stoped OK${TEXT_RES}" && return 0
    echo >&2 "${TEXT_RED}${1} not running${TEXT_RES}"
    ;;
  restart)
    sig TERM
    run "$CMD"
    echo "${TEXT_GRN}${1} reloaded OK${TEXT_RES}"
    return 0
    ;;
  *)
    echo >&2 "${TEXT_YEL}Usage: $(basename "$0") -c <start|stop|restart|force-stop> [-e <environment_name>][-i <instance_name>]${TEXT_RES}"
    exit 1
    ;;
  esac
}

if [ -z $INSTANCE ]; then
  for f in /etc/unicorn/*.conf
  do
    if test -f "$f"; then
      run_task $(basename "${f%%.*}")
    fi
  done
  exit 0
else
  run_task $INSTANCE
  exit 0
fi

